### ISSUE TITLE
Request Error

### ISSUE THREAD

**Issue by Suboms** [TUVIMEN/hdporncomics#2]
I get the error below when I try to make a request
```
Traceback (most recent call last):                                      File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/treerequests/session.py", line 260, in r_req
    resp.raise_for_status()                                             File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/requests/models.py", line 1026, in raise_for_status                        raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://hdporncomics.com/manhwa/an-introduction-to-milfs-manhwa-porn/

During handling of the above exception, another exception occurred:
                                                                      Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/hdporncomics", line 8, in <module>
    sys.exit(main())                                                               ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/hdporncomics/__init__.py", line 12, in main
    cli(sys.argv[1:] if sys.argv[1:] else ["-h"])                       File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/hdporncomics/cli.py", line 269, in cli
    guess(path, hdpo, url, osettings)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/hdporncomics/cli.py", line 32, in guess
    manhwa(path, hdpo, url, settings)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/hdporncomics/cli.py", line 218, in manhwa
    get_comiclike(path, hdpo, url, hdpo.get_manhwa, get_manhwa_chapters, settings)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/hdporncomics/cli.py", line 180, in get_comiclike
    r = func(url)
        ^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/hdporncomics/hdporncomics.py", line 459, in get_manhwa
    rq = self.ses.get_html(url)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/treerequests/session.py", line 298, in get_html
    resp = self.get(url, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/treerequests/session.py", line 274, in get
    return self.r_req(url, settings, method="get")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/treerequests/session.py", line 263, in r_req
    raise requesterror()
hdporncomics.hdporncomics.RequestError
```
And here is the command I used
`hdporncomics --directory . --cookie Cookies.txt 'https://hdporncomics.com/manhwa/an-introduction-to-milfs-manhwa-porn/'` and when that didn't work I used this `hdporncomics --directory . \
-b '_gid=GA1.2.353804985.1750674990' \
-b '_ga_6KJ6X1YHRG=GS2.1.s1750674958$o1$g1$t1750675289$j59$l0$h0' \
-b '_ga=GA1.2.861133619.1750674959' \
'https://hdporncomics.com/manhwa/an-introduction-to-milfs-manhwa-porn/'` and I still get the same issue.

I know the error is probably as a result of the cloudflare security check, how does one bypass it

**Comment by TUVIMEN** [comment]
First update the package, i found that they give slightly incorrect links to manhwa chapters that get redirected. Redirections are disallowed by default since you can pass credentials to account in requests - I've fixed the links.

When retrying remove `An Introduction to MILFs` directory, because this script doesn't overwrite them by default.

If passing cookies directly doesn't help in avoiding cloudflare you can install `browser_cookie3` package. They you can open any browser (not in incognito mode) and use `--browser YOUR-BROWSER` option, it can be `firefox`, `chrome`, `chromium` etc. (i don't know how it'll work on android). It will copy cookies from your browser, make sure you trigger the protection and fill the verification form.

It's weird it doesn't allow you to download even a chapter, here in europe you can make hundreds of requests per second without getting flagged.

**Comment by Suboms** [comment]
So I tried using the above fix and I still get the initial error i.e the request error
[Here is my cookie fike](https://rapidfire.olasubomi.workers.dev/0:/TheGdriveXbot/Cookies.txt)

**Comment by TUVIMEN** [comment]
Give me output of

```
curl -D - 'https://hdporncomics.com/manhwa/an-introduction-to-milfs-manhwa-porn/'
```

If you get 403, also get output of

```
curl -D - $(conv_cookies cookies.txt) 'https://hdporncomics.com/manhwa/an-introduction-to-milfs-manhwa-porn/'
```

**Comment by TUVIMEN** [comment]
Then it's not an issue of this program but your internet, consider using proxies/vpn

**Comment by Suboms** [comment]
Bro can you please add your setup.py file or its equivalent to make setup easy for me as I am making changes to the code on my mobile phone
